### ISSUE TITLE
Console is spammed with errors

### ISSUE THREAD

**Issue by CalaMariGold** [Laike-Endaril/Set-Bonus#11]
Console gets spammed with unfixable errors:

`[19:45:23] [Server thread/INFO] [STDERR]: [com.fantasticsource.setbonus.common.bonuselements.ModifierBonus:getInstance:38]: Not enough arguments for attribute bonus:`

I assumed "getInstance:38" is the line number, but it doesn't make sense.

Log with the config: https://drive.google.com/open?id=1ckIeppMuljmDjnLuyWM_ZEBMu_bECqRW

**Comment by Laike-Endaril** [comment]
It's very likely complaining about the empty entries.  Looks like you're using them for spacers between sections for organization.

That debug message normally prints out what you typed into the config so you know which entry to look at in order to fix something.  In this case the entries are empty, so it prints nothing.

I can probably go ahead and have it ignore empty lines.  Give me a bit and I'll have a new build out.

**Comment by Laike-Endaril** [comment]
This is now fixed / supported in the latest release (018)
