### ISSUE TITLE
[Suggestion] Hide particles for potion effects

### ISSUE THREAD

**Issue by ghost** [Laike-Endaril/Set-Bonus#17]
Would be nice to have a config option to disable particles for potion effects.

**Comment by Laike-Endaril** [comment]
Not a bad idea.

I've been trying to avoid doing much work on Set Bonus because it might get re-made as part of another mod, but I might take a look at this.  I might even do a real update since I'm not sure how long the new mod will take or if it will take over Set Bonus's features for sure, but no promises

**Comment by Laike-Endaril** [comment]
I assume the reasoning here is that your *own* particles are getting out of hand, right?

After thinking about it, it seems like you'd want to see particles on other players since you don't normally have another indicator...

**Comment by ghost** [comment]
Yup, too many particles on my end

**Comment by Laike-Endaril** [comment]
I believe this mod is the best solution:
[https://www.curseforge.com/minecraft/mc-mods/cleanview/files/2533542](https://www.curseforge.com/minecraft/mc-mods/cleanview/files/2533542)

Just to reiterate, I don't want to remove all particles from set potion effects, since they're valid indicators of what effects another player has on them.  The linked mod only removes particles emitted from yourself.

Since I'm fairly sure this is what you're going for, I'm going to close this issue.
